server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    password: root
    url: jdbc:mysql://localhost/registration?useSSL=false
    username: root
    dbname: registration
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hiberante:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    show-sql: true
